### PR TITLE
Add how-to use a custom CollectorRegistry to README

### PR DESCRIPTION
**Pull request by sumeetgajjar**

### CODE REVIEW

**Comment by sumeetgajjar** [comment]
Hi @dinowernli @ashamukov - can you please take a look at this PR?

**Review by dinowernli — CHANGES_REQUESTED** [review]
@sumeetgajjar not sure we necessarily want this change. If specifying a registry is optional, we'd probably want to keep the simplest setup possible in the documentation.

How about just adding a separate section to the docs along the lines of "Custom collector registries" or similar? That section could contain information for both client and server side.

**Comment by sumeetgajjar** [comment]
> @sumeetgajjar not sure we necessarily want this change. If specifying a registry is optional, we'd probably want to keep the simplest setup possible in the documentation.
> 
> How about just adding a separate section to the docs along the lines of "Custom collector registries" or similar? That section could contain information for both client and server side.

Thanks for the suggestion @dinowernli, made the corresponding changes.
Please review and let me know if any further changes are required.

**Review by dinowernli — APPROVED** [review]
LGTM, thank you

**Pull request merged**
